# Generated by Django 4.1.7 on 2023-03-02 09:07

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_task_description_task_end_time_task_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                default=django.contrib.gis.geos.point.Point(0.0, 0.0),
                geography=True,
                null=True,
                srid=4326,
            ),
        ),
    ]
