# Generated by Django 4.1.7 on 2023-03-02 09:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_task_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
    ]
