# Generated by Django 4.1.7 on 2023-04-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_alter_task_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="location",
        ),
        migrations.AddField(
            model_name="task",
            name="notify",
            field=models.BooleanField(default=False),
        ),
    ]
